//! Integration coverage for the compiler's supporting Cargo tooling.

use behave::prelude::*;
use luau_rs::{
    decode_module, translate_module, DecodeOutcome, MainInvocation, TranslateOptions,
    TranslateOutcome, TranslationRejection, WasmDecodeProblemReason, WasmDecodeRejection,
};
use proptest::prelude::*;
use walrus::{FunctionBuilder, Module, ValType};

#[allow(dead_code)]
struct ToolingIntegration;

#[derive(Debug, thiserror::Error, miette::Diagnostic)]
enum ToolingFailure {
    #[error("wasm-smith could not generate a module: {source}")]
    #[diagnostic(code(luau_rs::tooling::smith_generation))]
    SmithGeneration {
        #[source]
        source: arbitrary::Error,
    },

    #[error("wasmparser rejected generated bytes: {source}")]
    #[diagnostic(code(luau_rs::tooling::wasm_validation))]
    WasmValidation {
        #[source]
        source: wasmparser::BinaryReaderError,
    },

    #[error("wasm-mutate could not start: {source}")]
    #[diagnostic(code(luau_rs::tooling::wasm_mutation))]
    WasmMutation {
        #[source]
        source: wasm_mutate::Error,
    },

    #[error("wasm-shrink could not reduce the module: {source}")]
    #[diagnostic(code(luau_rs::tooling::wasm_shrink))]
    WasmShrink {
        #[source]
        source: anyhow::Error,
    },

    #[error("decode rejected the {stage} module: {rejection:?}")]
    #[diagnostic(code(luau_rs::tooling::decode_rejection))]
    DecodeRejected {
        stage: &'static str,
        rejection: WasmDecodeRejection,
    },

    #[error("translation rejected the fixture: {rejection:?}")]
    #[diagnostic(code(luau_rs::tooling::translation_rejection))]
    TranslationRejected { rejection: TranslationRejection },

    #[error("full_moon rejected generated Luau: {errors:?}")]
    #[diagnostic(code(luau_rs::tooling::luau_parse))]
    LuauParse { errors: Vec<full_moon::Error> },

    #[error("mlua could not compile generated Luau: {source}")]
    #[diagnostic(code(luau_rs::tooling::luau_compile))]
    LuauCompile {
        #[source]
        source: mlua::Error,
    },

    #[error("miette rendered {rendered:?}; expected it to contain {expected:?}")]
    #[diagnostic(code(luau_rs::tooling::diagnostic_rendering))]
    DiagnosticMismatch {
        rendered: String,
        expected: &'static str,
    },
}

type ToolingResult<T> = Result<T, ToolingFailure>;

fn bounded_smith_module() -> ToolingResult<Vec<u8>> {
    let mut config = wasm_smith::Config {
        allow_start_export: false,
        allow_floats: false,
        bulk_memory_enabled: false,
        exceptions_enabled: false,
        gc_enabled: false,
        max_data_segments: 2,
        max_element_segments: 2,
        max_funcs: 3,
        max_globals: 2,
        max_imports: 0,
        max_instructions: 24,
        max_memories: 1,
        max_tables: 0,
        memory64_enabled: false,
        reference_types_enabled: false,
        simd_enabled: false,
        tail_call_enabled: false,
        threads_enabled: false,
        ..wasm_smith::Config::default()
    };
    config.max_types = 6;
    config.max_exports = 3;
    config.max_type_size = 24;
    config.max_memory32_bytes = 65_536;
    config.max_table_elements = 0;
    config.max_tags = 0;
    config.max_values = 0;
    config.min_funcs = 1;

    let seed = [0x42; 4096];
    let mut input = arbitrary::Unstructured::new(&seed);
    match wasm_smith::Module::new(config, &mut input) {
        Ok(module) => Ok(module.to_bytes()),
        Err(source) => Err(ToolingFailure::SmithGeneration { source }),
    }
}

fn validate_wasm(bytes: &[u8]) -> ToolingResult<()> {
    let mut validator = wasmparser::Validator::new_with_features(wasmparser::WasmFeatures::all());
    match validator.validate_all(bytes) {
        Ok(_) => Ok(()),
        Err(source) => Err(ToolingFailure::WasmValidation { source }),
    }
}

fn mutate_wasm(bytes: &[u8]) -> ToolingResult<Vec<u8>> {
    let mut mutator = wasm_mutate::WasmMutate::default();
    mutator.seed(7).preserve_semantics(true).fuel(128);
    let mut candidates = match mutator.run(bytes) {
        Ok(candidates) => candidates,
        Err(source) => return Err(ToolingFailure::WasmMutation { source }),
    };
    match candidates.next() {
        Some(Ok(candidate)) => Ok(candidate),
        Some(Err(source)) => Err(ToolingFailure::WasmMutation { source }),
        None => Ok(bytes.to_vec()),
    }
}

fn shrink_wasm(bytes: Vec<u8>) -> ToolingResult<Vec<u8>> {
    let shrinker = wasm_shrink::WasmShrink::default()
        .attempts(4)
        .allow_empty(false)
        .seed(7);
    match shrinker.run(bytes, |candidate| {
        Ok::<bool, anyhow::Error>(candidate.len() > 8)
    }) {
        Ok(info) => Ok(info.output),
        Err(source) => Err(ToolingFailure::WasmShrink { source }),
    }
}

fn decode_fixture(bytes: &[u8], stage: &'static str) -> ToolingResult<luau_rs::DecodedModule> {
    match decode_module(bytes) {
        DecodeOutcome::Decoded(decoded) => Ok(*decoded),
        DecodeOutcome::Rejected(rejection) => {
            Err(ToolingFailure::DecodeRejected { stage, rejection })
        }
    }
}

fn exercise_generated_wasm() -> ToolingResult<()> {
    let generated = bounded_smith_module()?;
    validate_wasm(&generated)?;

    match decode_module(&generated) {
        DecodeOutcome::Decoded(_) | DecodeOutcome::Rejected(_) => {}
    }

    let mutated = mutate_wasm(&generated)?;
    validate_wasm(&mutated)?;
    match decode_module(&mutated) {
        DecodeOutcome::Decoded(_) | DecodeOutcome::Rejected(_) => {}
    }

    let shrunk = shrink_wasm(mutated)?;
    validate_wasm(&shrunk)?;
    match decode_module(&shrunk) {
        DecodeOutcome::Decoded(_) | DecodeOutcome::Rejected(_) => {}
    }
    Ok(())
}

fn luau_fixture() -> ToolingResult<String> {
    let mut module = Module::default();
    let mut builder = FunctionBuilder::new(&mut module.types, &[], &[ValType::I32]);
    builder.func_body().i32_const(42);
    let function = builder.finish(Vec::new(), &mut module.funcs);
    module.exports.add("answer", function);

    let decoded = decode_fixture(&module.emit_wasm(), "Luau")?;
    match translate_module(
        &decoded,
        TranslateOptions::with_main_invocation(MainInvocation::LeaveIdle),
    ) {
        TranslateOutcome::Translated(artifact) => Ok(artifact.into_text()),
        TranslateOutcome::Rejected(rejection) => {
            Err(ToolingFailure::TranslationRejected { rejection })
        }
    }
}

fn exercise_luau_boundaries() -> ToolingResult<()> {
    let source = luau_fixture()?;
    let parsed = full_moon::parse_fallible(&source, full_moon::LuaVersion::luau());
    if !parsed.errors().is_empty() {
        return Err(ToolingFailure::LuauParse {
            errors: parsed.errors().to_vec(),
        });
    }

    let lua = mlua::Lua::new();
    match lua.load(&source).set_name("generated").into_function() {
        Ok(_) => Ok(()),
        Err(source) => Err(ToolingFailure::LuauCompile { source }),
    }
}

fn exercise_diagnostics() -> ToolingResult<()> {
    let problem = WasmDecodeProblemReason::UnsupportedMemoryCount { count: 2 };
    let report = miette::Report::from_err(problem);
    let rendered = report.to_string();
    let expected = "module declares 2 memories";
    if rendered.contains(expected) {
        Ok(())
    } else {
        Err(ToolingFailure::DiagnosticMismatch { rendered, expected })
    }
}

fn i64_fixture(value: i64) -> ToolingResult<String> {
    let mut module = Module::default();
    let mut builder = FunctionBuilder::new(&mut module.types, &[], &[ValType::I64]);
    builder.func_body().i64_const(value);
    let function = builder.finish(Vec::new(), &mut module.funcs);
    module.exports.add("value", function);

    let decoded = decode_fixture(&module.emit_wasm(), "i64")?;
    match translate_module(
        &decoded,
        TranslateOptions::with_main_invocation(MainInvocation::LeaveIdle),
    ) {
        TranslateOutcome::Translated(artifact) => Ok(artifact.into_text()),
        TranslateOutcome::Rejected(rejection) => {
            Err(ToolingFailure::TranslationRejected { rejection })
        }
    }
}

behave! {
    "compiler tooling" {
        "generated and reduced WebAssembly stays valid" {
            expect!(exercise_generated_wasm()).to_be_ok()?;
        }

        "generated Luau crosses parser and embedded compiler boundaries" {
            expect!(exercise_luau_boundaries()).to_be_ok()?;
        }

        "typed decoder errors remain readable through miette" {
            expect!(exercise_diagnostics()).to_be_ok()?;
        }
    }
}

proptest! {
    #[test]
    fn generated_i64_literals_include_both_unsigned_halves(value in any::<i64>()) {
        let source_result = i64_fixture(value);
        prop_assert_eq!(source_result.is_ok(), true, "could not translate i64 fixture");
        let source = match source_result {
            Ok(source) => source,
            Err(error) => {
                prop_assert_eq!(
                    error.to_string().is_empty(),
                    true,
                    "unexpected i64 error: {}",
                    error
                );
                return Ok(());
            }
        };
        let bits = u64::from_ne_bytes(value.to_ne_bytes());
        let low = (bits & 0xffff_ffff).to_string();
        let high = (bits >> 32).to_string();
        prop_assert_eq!(
            source.contains(&low),
            true,
            "missing low i64 half {} in {}",
            low,
            source
        );
        prop_assert_eq!(
            source.contains(&high),
            true,
            "missing high i64 half {} in {}",
            high,
            source
        );
    }
}
