//! Module-level Luau emission: instantiation factory, memory, globals,
//! import proxies, data segments, exports, and the entrypoint invocation.

use crate::wasm::{
    DecodedDataSegmentKind, DecodedExport, DecodedFunction, DecodedFunctionBody,
    DecodedGlobalValue, DecodedModule, StartFunctionPresence,
};
use std::collections::{HashMap, HashSet, VecDeque};
use walrus::ir::{dfs_in_order, Visitor};
use walrus::FunctionKind;

use super::function::{emit_function_body, function_signature, FunctionBodyInput};
use super::helpers::HELPER_SOURCE;
use super::problem::TranslationProblemReason;
use super::writer::{
    luau_byte_string, luau_number_literal, luau_string_literal, usize_from_u32, TextWriter,
};

/// The default growth cap in pages when the module declares no maximum.
const DEFAULT_MAXIMUM_PAGES: u32 = 1_024;

const fn declared_maximum_pages(pages: u32) -> u32 {
    pages
}

/// The imports parameter name inside the generated factory.
const IMPORTS_NAME: &str = "imports";

/// Whether the generated module runs its exported `main` function.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MainInvocation {
    /// Invoke `WASM_EXPORTS.main` after instantiation.
    InvokeMain,
    /// Leave every export idle; callers own the entrypoint.
    LeaveIdle,
}

/// Options that control one module translation.
#[derive(Debug, Clone, Copy)]
pub struct TranslateOptions {
    main_invocation: MainInvocation,
}

impl TranslateOptions {
    /// @why Lets callers choose whether the generated module runs its `main` export.
    #[must_use]
    pub const fn with_main_invocation(main_invocation: MainInvocation) -> Self {
        Self { main_invocation }
    }
}

/// Emits the complete strict Luau module for one decoded wasm module.
pub fn emit_module(
    decoded: &DecodedModule,
    options: TranslateOptions,
) -> Result<String, TranslationProblemReason> {
    let reachable = reachable_function_indices(decoded)?;
    let mut writer = TextWriter::new();
    writer.line("--!strict");
    writer.line("");
    writer.line("-- Generated by luau-rs from a wasm module.");
    writer.line("-- Instantiate with the module's imports table:");
    writer.line("--   local instance = require(module)(imports)");
    writer.line("");
    writer.raw(HELPER_SOURCE);
    writer.line("");

    writer.line(&format!(
        "local function instantiate({IMPORTS_NAME}: {{[string]: {{[string]: any}}}}): {{[string]: any}}"
    ));
    writer.push_indent();
    writer.line(&format!("local WASM_IMPORTS = {IMPORTS_NAME}"));
    emit_function_name_declarations(decoded, &reachable, &mut writer);

    emit_memory(decoded, &mut writer);
    emit_globals(decoded, &mut writer);
    writer.line("local FUNCTIONS: {any} = {}");

    emit_functions(decoded, &reachable, &mut writer)?;
    emit_data_segments(decoded, &mut writer);
    emit_element_segments(decoded, &reachable, &mut writer)?;
    emit_start(decoded, &mut writer);
    emit_exports(decoded, &mut writer);
    emit_main_invocation(decoded, options, &mut writer);

    writer.line("return WASM_EXPORTS");
    writer.pop_indent();
    writer.line("end");
    writer.line("");
    writer.line("return instantiate");

    Ok(writer.finish())
}

/// Declares every `FUNC_N` name before any body is emitted, so wasm index
/// order never shadows call order and recursion resolves. The names are typed
/// `any` so strict analysis allows calls before a body is assigned.
fn emit_function_name_declarations(
    decoded: &DecodedModule,
    reachable: &HashSet<usize>,
    writer: &mut TextWriter,
) {
    let names = decoded
        .functions()
        .iter()
        .filter(|function| reachable.contains(&function.index()))
        .map(|function| format!("FUNC_{}: any", function.index()))
        .collect::<Vec<_>>();
    writer.line(&format!("local {}", names.join(", ")));
}

fn emit_memory(decoded: &DecodedModule, writer: &mut TextWriter) {
    let Some(memory) = decoded.memory() else {
        return;
    };
    let byte_size =
        u64::from(memory.initial_pages()) * u64::from(super::writer::WASM_PAGE_SIZE_BYTES);
    let maximum_pages = memory
        .maximum_pages()
        .map_or(DEFAULT_MAXIMUM_PAGES, declared_maximum_pages);
    writer.line(&format!(
        "local MEMORY: buffer = buffer.create({byte_size})"
    ));
    writer.line(&format!(
        "local MEMORY_PAGES: number = {}",
        memory.initial_pages()
    ));
    writer.line(&format!("local MAXIMUM_PAGES: number = {maximum_pages}"));
}

fn emit_globals(decoded: &DecodedModule, writer: &mut TextWriter) {
    if decoded.globals().is_empty() {
        return;
    }
    let mut entries = Vec::new();
    let mut slot_index = 0;
    for global in decoded.globals() {
        match global.initial_value() {
            DecodedGlobalValue::I64(value) => {
                let (low, high) = super::ops::luau_i64_parts(value);
                entries.push(format!(
                    "[{}] = {low}, [{}] = {high}",
                    slot_index + super::writer::LUAU_INDEX_OFFSET,
                    slot_index + super::writer::LUAU_INDEX_OFFSET + 1
                ));
                slot_index += 2;
            }
            DecodedGlobalValue::I32(value) => {
                entries.push(format!(
                    "[{}] = {}",
                    slot_index + super::writer::LUAU_INDEX_OFFSET,
                    value
                ));
                slot_index += 1;
            }
            DecodedGlobalValue::F32(value) => {
                entries.push(format!(
                    "[{}] = {}",
                    slot_index + super::writer::LUAU_INDEX_OFFSET,
                    luau_number_literal(f64::from(value))
                ));
                slot_index += 1;
            }
            DecodedGlobalValue::F64(value) => {
                entries.push(format!(
                    "[{}] = {}",
                    slot_index + super::writer::LUAU_INDEX_OFFSET,
                    luau_number_literal(value)
                ));
                slot_index += 1;
            }
            DecodedGlobalValue::NullReference => {
                entries.push(format!(
                    "[{}] = nil",
                    slot_index + super::writer::LUAU_INDEX_OFFSET
                ));
                slot_index += 1;
            }
        }
    }
    writer.line(&format!(
        "local GLOBALS: {{any}} = {{ {} }}",
        entries.join(", ")
    ));
}

fn emit_functions(
    decoded: &DecodedModule,
    reachable: &HashSet<usize>,
    writer: &mut TextWriter,
) -> Result<(), TranslationProblemReason> {
    let import_routes = import_routes_by_index(decoded);
    let module = decoded.walrus_module();
    for function in decoded.functions() {
        if !reachable.contains(&function.index()) {
            continue;
        }
        if should_stub_panic(function) {
            emit_panic_stub(function, writer);
            continue;
        }
        match function.body() {
            DecodedFunctionBody::Imported => {
                emit_import_proxy(function, &import_routes, writer)?;
            }
            DecodedFunctionBody::Defined { entry_sequence } => {
                let local_function = find_local_function(module, function.index())?;
                let input = FunctionBodyInput {
                    function,
                    local_function,
                    module,
                    entry_sequence: *entry_sequence,
                };
                emit_function_body(&input, writer)?;
            }
        }
    }
    Ok(())
}

/// Handles runtime functions that deliberately terminate execution.
/// Identifies Rust runtime paths whose only supported outcome is a wasm trap.
fn should_stub_panic(function: &DecodedFunction) -> bool {
    function
        .name()
        .is_some_and(|name| name.contains("panic") || name.contains("rust_oom"))
}

/// Replaces host-side panic formatting with the backend's deterministic trap.
fn emit_panic_stub(function: &DecodedFunction, writer: &mut TextWriter) {
    let (parameters, return_annotation) = function_signature(function);
    let comment_name = function
        .name()
        .map_or_else(String::new, |name| format!(" -- {name}"));
    if return_annotation.is_empty() {
        writer.line(&format!(
            "FUNC_{} = function({}){}",
            function.index(),
            parameters.join(", "),
            comment_name
        ));
    } else {
        writer.line(&format!(
            "FUNC_{} = function({}): {}{}",
            function.index(),
            parameters.join(", "),
            return_annotation,
            comment_name
        ));
    }
    writer.push_indent();
    writer.line("error(\"wasm trap: panic\")");
    writer.pop_indent();
    writer.line("end");
    writer.line("");
}

/// Computes the function closure that the generated module can execute.
fn reachable_function_indices(
    decoded: &DecodedModule,
) -> Result<HashSet<usize>, TranslationProblemReason> {
    let mut reachable = HashSet::new();
    for export in decoded.exports() {
        if let DecodedExport::Function { function_index, .. } = export {
            reachable.insert(*function_index);
        }
    }
    if let Some(function_index) = decoded.start_function().function_index() {
        reachable.insert(function_index);
    }

    let mut pending = reachable.iter().copied().collect::<VecDeque<_>>();
    let mut includes_indirect_targets = false;
    while let Some(function_index) = pending.pop_front() {
        let Some(function) = decoded
            .functions()
            .iter()
            .find(|candidate| candidate.index() == function_index)
        else {
            continue;
        };
        let DecodedFunctionBody::Defined { entry_sequence } = function.body() else {
            continue;
        };
        let local_function = find_local_function(decoded.walrus_module(), function_index)?;
        let mut references = FunctionReferenceCollector::default();
        dfs_in_order(&mut references, local_function, *entry_sequence);
        if references.uses_indirect_calls && !includes_indirect_targets {
            includes_indirect_targets = true;
            for segment in decoded.element_segments() {
                for function_index in segment.function_indices() {
                    if reachable.insert(*function_index) {
                        pending.push_back(*function_index);
                    }
                }
            }
        }
        for referenced in references.functions {
            if reachable.insert(referenced) {
                pending.push_back(referenced);
            }
        }
    }
    Ok(reachable)
}

#[derive(Default)]
struct FunctionReferenceCollector {
    functions: Vec<usize>,
    uses_indirect_calls: bool,
}

impl<'instr> Visitor<'instr> for FunctionReferenceCollector {
    fn visit_instr(
        &mut self,
        instruction: &'instr walrus::ir::Instr,
        _location: &'instr walrus::ir::InstrLocId,
    ) {
        if matches!(
            instruction,
            walrus::ir::Instr::CallIndirect(..) | walrus::ir::Instr::ReturnCallIndirect(..)
        ) {
            self.uses_indirect_calls = true;
        }
    }

    fn visit_function_id(&mut self, function: &walrus::FunctionId) {
        self.functions.push(function.index());
    }
}

/// Maps imported functions to their module routes.
fn import_routes_by_index(decoded: &DecodedModule) -> HashMap<usize, (String, String)> {
    let mut routes = HashMap::new();
    for import in decoded.imports() {
        routes.insert(
            import.function_index(),
            (import.module().to_string(), import.name().to_string()),
        );
    }
    routes
}

fn emit_import_proxy(
    function: &DecodedFunction,
    import_routes: &HashMap<usize, (String, String)>,
    writer: &mut TextWriter,
) -> Result<(), TranslationProblemReason> {
    let route = import_routes.get(&function.index()).ok_or_else(|| {
        TranslationProblemReason::Internal(format!(
            "imported function {} has no import route",
            function.index()
        ))
    })?;
    let (parameters, return_annotation) = function_signature(function);
    if return_annotation.is_empty() {
        writer.line(&format!(
            "FUNC_{} = function({})",
            function.index(),
            parameters.join(", ")
        ));
    } else {
        writer.line(&format!(
            "FUNC_{} = function({}): {}",
            function.index(),
            parameters.join(", "),
            return_annotation
        ));
    }
    writer.push_indent();
    let parameter_names = function
        .params()
        .iter()
        .enumerate()
        .flat_map(|(index, value_type)| {
            if *value_type == crate::wasm::WasmValueType::I64 {
                vec![format!("p{index}_lo"), format!("p{index}_hi")]
            } else {
                vec![format!("p{index}")]
            }
        })
        .collect::<Vec<_>>();
    writer.line(&format!(
        "return WASM_IMPORTS[{}][{}]({})",
        luau_string_literal(&route.0),
        luau_string_literal(&route.1),
        parameter_names.join(", ")
    ));
    writer.pop_indent();
    writer.line("end");
    writer.line("");
    Ok(())
}

fn find_local_function(
    module: &walrus::Module,
    function_index: usize,
) -> Result<&walrus::LocalFunction, TranslationProblemReason> {
    for function in module.funcs.iter() {
        if function.id().index() != function_index {
            continue;
        }
        match &function.kind {
            FunctionKind::Local(local_function) => return Ok(local_function),
            FunctionKind::Import(_) | FunctionKind::Uninitialized(_) => {
                return Err(TranslationProblemReason::Internal(format!(
                    "function {function_index} is not local"
                )));
            }
        }
    }
    Err(TranslationProblemReason::Internal(format!(
        "function {function_index} not found in module"
    )))
}

fn emit_data_segments(decoded: &DecodedModule, writer: &mut TextWriter) {
    for (index, segment) in decoded.data_segments().iter().enumerate() {
        let byte_literal = luau_byte_string(segment.bytes());
        match segment.kind() {
            DecodedDataSegmentKind::Active { offset } => {
                writer.line(&format!(
                    "buffer.writestring(MEMORY, {offset}, {byte_literal})"
                ));
            }
            DecodedDataSegmentKind::Passive => {
                writer.line(&format!(
                    "local DATA_{index}: buffer = buffer.create({})",
                    segment.bytes().len()
                ));
                writer.line(&format!(
                    "buffer.writestring(DATA_{index}, 0, {byte_literal})"
                ));
            }
        }
    }
}

fn emit_element_segments(
    decoded: &DecodedModule,
    reachable: &HashSet<usize>,
    writer: &mut TextWriter,
) -> Result<(), TranslationProblemReason> {
    for segment in decoded.element_segments() {
        let table_offset = usize_from_u32(segment.table_offset())?;
        for (position, function_index) in segment.function_indices().iter().enumerate() {
            if !reachable.contains(function_index) {
                continue;
            }
            writer.line(&format!(
                "FUNCTIONS[{}] = FUNC_{function_index}",
                table_offset + position + super::writer::LUAU_INDEX_OFFSET
            ));
        }
    }
    Ok(())
}

fn emit_start(decoded: &DecodedModule, writer: &mut TextWriter) {
    match decoded.start_function() {
        StartFunctionPresence::Declared { function_index } => {
            writer.line(&format!("FUNC_{function_index}()"));
        }
        StartFunctionPresence::Absent => {}
    }
}

fn emit_exports(decoded: &DecodedModule, writer: &mut TextWriter) {
    let mut entries = Vec::new();
    for export in decoded.exports() {
        match export {
            DecodedExport::Function {
                name,
                function_index,
            } => {
                entries.push(format!(
                    "[{}] = FUNC_{function_index}",
                    luau_string_literal(name)
                ));
            }
            DecodedExport::Memory { name } => {
                entries.push(format!("[{}] = MEMORY", luau_string_literal(name)));
            }
        }
    }
    // The indirect-call table is always exported so the Roblox runtime can
    // invoke Rust callbacks registered through imports (events).
    entries.push("[\"functions\"] = FUNCTIONS".to_string());
    writer.line(&format!(
        "local WASM_EXPORTS: {{[string]: any}} = {{ {} }}",
        entries.join(", ")
    ));
}

fn emit_main_invocation(
    decoded: &DecodedModule,
    options: TranslateOptions,
    writer: &mut TextWriter,
) {
    if options.main_invocation == MainInvocation::LeaveIdle {
        return;
    }
    let has_main_export = decoded.exports().iter().any(|export| {
        matches!(
            export,
            DecodedExport::Function { name, .. } if name == "main"
        )
    });
    if has_main_export {
        writer.line("if WASM_EXPORTS.main ~= nil then");
        writer.push_indent();
        writer.line("WASM_EXPORTS.main()");
        writer.pop_indent();
        writer.line("end");
    }
}
